from dh_segment_torch.models.encoders.encoder import Encoder
from dh_segment_torch.models.encoders.resnet import ResNetEncoder
from dh_segment_torch.models.encoders.mobilenet import MobileNetV2Encoder